### ISSUE TITLE
Can't get WAD to upload to S3

### ISSUE THREAD

**Issue by JonRCahill** [Fingertips/WAD#7]
I am attempting to use WAD, followed the instructions on the README but I keep getting and error when it attempts to upload. The error is:

[wad] Creating Wad with tar (/home/travis/build/Zero41/Prezentt/tmp/8fd22b914a8340946c3a81db8c947aba.tar.bz2)
[wad] Trying to write Wad to S3
/home/travis/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/openssl/buffering.rb:318:in `syswrite': Connection reset by peer (Errno::ECONNRESET)
    from /home/travis/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/openssl/buffering.rb:318:in`do_write'
    from /home/travis/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/openssl/buffering.rb:336:in `write'
    from /home/travis/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/protocol.rb:199:in`write0'
    from /home/travis/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/protocol.rb:173:in `block in write'
    from /home/travis/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/protocol.rb:190:in`writing'
    from /home/travis/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/protocol.rb:172:in `write'
    from /home/travis/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:1938:in`send_request_with_body'
    from /home/travis/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:1920:in `exec'
    from /home/travis/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:1318:in`block in transport_request'
    from /home/travis/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
    from /home/travis/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:1317:in`transport_request'
    from /home/travis/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:1294:in `request'
    from bin/wad:176:in`block in put'
    from /home/travis/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:746:in `start'
    from bin/wad:176:in`put'
    from bin/wad:212:in `put'
    from bin/wad:307:in`s3_write'
    from bin/wad:345:in `put'
    from bin/wad:366:in`setup'
    from bin/wad:377:in `setup'
    from bin/wad:386:in`<main>'
The command "bin/wad" failed and exited with 1 during install.

Any help with this would be appreciated.

**Comment by Manfred** [comment]
Can you share your Travis configuration? Or at least the configured variables?

**Comment by JonRCahill** [comment]
Here is what I have, I have taken out the sensitive information:

```
install: "bin/wad"
language: ruby
rvm:
  - 1.9.3
before_script:
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate
script:
  - bundle exec rspec spec
  - bundle exec teaspoon -q
  - bundle exec cucumber --format progress
deploy:
  provider: heroku
  api_key:
    secure: <snip>
  run: rake db:migrate
  app:
    master: <snip>
    staging: <snip>
    production: <snip>
env:
  global:
  - S3_BUCKET_NAME=Zero41
  - secure: <snip>
```

Other than trying to use the install: "bin/wad" option it all does work correctly, just with 8min bundler times :(

**Comment by JonRCahill** [comment]
I don't have the S3_REGION because my bucket is on us-east-1 but I just tried to set it explicitly and I get the same problem.

**Comment by Dakuan** [comment]
I am also having this issue

**Comment by Manfred** [comment]
@Dakuan Can you provide some more information, your Ruby version and Travis config or at least the env part?

**Comment by JonRCahill** [comment]
Ok, I spent a fair while trying to get to the bottom of this and ended up find out the problem was because my S3 bucket started with a capital letter. Going to http://Zero41.s3.amazonaws.com/ or http://zero41.s3.amazonaws.com/ would result in a "NoSuchBucket" from AWS. Deleting the bucket and creating it again with no capitals worked fine, sigh.

**Comment by Dakuan** [comment]
@BobaFaux My bucket starts with a lowercase :(

@Manfred I'm on Ruby 1.9.3

.travis.yml:

```
language: node_js
node_js:
  - 0.10
env:
  global:
    - S3_BUCKET_NAME=...
    - S3_REGION=eu-west-1
    - secure: "..."
notifications:
  hipchat: ...
before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
 - "scripts/wad"
before_script:
  - npm install -g grunt-cli
branches:
  only:
    - master
    - develop
addons:
  hosts: 
    - ...
    - ...
deploy:
  provider: heroku
  api_key: "..."
  app: 
    develop: ...
    master: ...
```
